AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  HTTP API that gets, creates and deletes YouTube url videos in DynamoDB
  
Globals:
  Function:
    Timeout: 10

Resources:
  DDBHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: aws-lambda/
      Handler: app.handler
      Runtime: nodejs12.x
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ItemsTable
      Events:
        GetAllVideos:
          Type: HttpApi
          Properties:
            Path: /videos
            Method: GET
        DeleteAVideo:
          Type: HttpApi
          Properties:
            Path: /videos/{id}
            Method: DELETE
        CORSDelete:
          Type: HttpApi
          Properties:
            Path: /videos/{id}
            Method: OPTIONS
        CORSCreate:
          Type: HttpApi
          Properties:
            Path: /videos
            Method: OPTIONS
        CreateVideo:
          Type: HttpApi
          Properties:
            Path: /videos
            Method: POST

  ItemsTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: String
      TableName: videos

Outputs:
  ApiEndpoint:
    Description: "The invoke URL for our HTTP API"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/videos"
  Function:
    Description: "DynamoDB handler function ARN"
    Value: !GetAtt DDBHandlerFunction.Arn
